// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RespiraAMS.Infrastructure.Data;

#nullable disable

namespace RespiraAMS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527095050_UpdateSpectrumModel")]
    partial class UpdateSpectrumModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AntibioticTreatmentProtocol", b =>
                {
                    b.Property<Guid>("MedicinesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreatmentProtocolId")
                        .HasColumnType("uuid");

                    b.HasKey("MedicinesId", "TreatmentProtocolId");

                    b.HasIndex("TreatmentProtocolId");

                    b.ToTable("AntibioticTreatmentProtocol");
                });

            modelBuilder.Entity("CriterionTreatmentProtocol", b =>
                {
                    b.Property<Guid>("OtherCriteriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreatmentProtocolId")
                        .HasColumnType("uuid");

                    b.HasKey("OtherCriteriaId", "TreatmentProtocolId");

                    b.HasIndex("TreatmentProtocolId");

                    b.ToTable("CriterionTreatmentProtocol");
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.Antibiotic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AntibioticSpectrumId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dosages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int[]>("RouteOfAdministrations")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AntibioticSpectrumId");

                    b.ToTable("antibiotics", (string)null);
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.AntibioticSpectrum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("antibiotic_spectra", (string)null);
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.Criterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("criteria", (string)null);

                    b.HasDiscriminator<string>("type").HasValue("Criterion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.Disease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredIcuMainCriteria")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredIcuSecondaryCriteria")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("diseases", (string)null);
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.DiseasePathogen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiseaseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PathogenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TreatmentSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("PathogenId");

                    b.ToTable("disease_pathogens", (string)null);
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.IcuHospitalizeCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiseaseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMainCriteria")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId")
                        .IsUnique();

                    b.HasIndex("DiseaseId");

                    b.ToTable("icu_hospitalize_criteria", (string)null);
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.Pathogen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("pathogens", (string)null);
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.ResistanceRiskFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiseaseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PathogenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId")
                        .IsUnique();

                    b.HasIndex("DiseaseId");

                    b.HasIndex("PathogenId");

                    b.ToTable("resistance_risk_factors", (string)null);
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.TreatmentProtocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiseaseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SpecialInfectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TreatmentSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("SpecialInfectionId");

                    b.ToTable("treatment_protocols", (string)null);
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.BooleanCriterion", b =>
                {
                    b.HasBaseType("RespiraAMS.Domain.Models.Criterion");

                    b.HasDiscriminator().HasValue("boolean");
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.NumericCriterion", b =>
                {
                    b.HasBaseType("RespiraAMS.Domain.Models.Criterion");

                    b.Property<bool>("IsExclusive")
                        .HasColumnType("boolean");

                    b.Property<double>("Max")
                        .HasColumnType("double precision");

                    b.Property<double>("Min")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("numeric");
                });

            modelBuilder.Entity("AntibioticTreatmentProtocol", b =>
                {
                    b.HasOne("RespiraAMS.Domain.Models.Antibiotic", null)
                        .WithMany()
                        .HasForeignKey("MedicinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespiraAMS.Domain.Models.TreatmentProtocol", null)
                        .WithMany()
                        .HasForeignKey("TreatmentProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CriterionTreatmentProtocol", b =>
                {
                    b.HasOne("RespiraAMS.Domain.Models.Criterion", null)
                        .WithMany()
                        .HasForeignKey("OtherCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespiraAMS.Domain.Models.TreatmentProtocol", null)
                        .WithMany()
                        .HasForeignKey("TreatmentProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.Antibiotic", b =>
                {
                    b.HasOne("RespiraAMS.Domain.Models.AntibioticSpectrum", "AntibioticSpectrum")
                        .WithMany("Antibiotics")
                        .HasForeignKey("AntibioticSpectrumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AntibioticSpectrum");
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.DiseasePathogen", b =>
                {
                    b.HasOne("RespiraAMS.Domain.Models.Disease", "Disease")
                        .WithMany("DiseasePathogens")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespiraAMS.Domain.Models.Pathogen", "Pathogen")
                        .WithMany("DiseasePathogens")
                        .HasForeignKey("PathogenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Pathogen");
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.IcuHospitalizeCriterion", b =>
                {
                    b.HasOne("RespiraAMS.Domain.Models.Criterion", "Criterion")
                        .WithOne()
                        .HasForeignKey("RespiraAMS.Domain.Models.IcuHospitalizeCriterion", "CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespiraAMS.Domain.Models.Disease", "Disease")
                        .WithMany("IcuHospitalizeCriteria")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("Disease");
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.ResistanceRiskFactor", b =>
                {
                    b.HasOne("RespiraAMS.Domain.Models.Criterion", "Criterion")
                        .WithOne()
                        .HasForeignKey("RespiraAMS.Domain.Models.ResistanceRiskFactor", "CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespiraAMS.Domain.Models.Disease", "Disease")
                        .WithMany("ResistanceRisks")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespiraAMS.Domain.Models.Pathogen", "Pathogen")
                        .WithMany("ResistanceRiskFactors")
                        .HasForeignKey("PathogenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("Disease");

                    b.Navigation("Pathogen");
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.TreatmentProtocol", b =>
                {
                    b.HasOne("RespiraAMS.Domain.Models.Disease", "Disease")
                        .WithMany("TreatmentProtocols")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespiraAMS.Domain.Models.Pathogen", "SpecialInfection")
                        .WithMany("TreatmentProtocols")
                        .HasForeignKey("SpecialInfectionId");

                    b.Navigation("Disease");

                    b.Navigation("SpecialInfection");
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.AntibioticSpectrum", b =>
                {
                    b.Navigation("Antibiotics");
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.Disease", b =>
                {
                    b.Navigation("DiseasePathogens");

                    b.Navigation("IcuHospitalizeCriteria");

                    b.Navigation("ResistanceRisks");

                    b.Navigation("TreatmentProtocols");
                });

            modelBuilder.Entity("RespiraAMS.Domain.Models.Pathogen", b =>
                {
                    b.Navigation("DiseasePathogens");

                    b.Navigation("ResistanceRiskFactors");

                    b.Navigation("TreatmentProtocols");
                });
#pragma warning restore 612, 618
        }
    }
}
