@RespiraAMS.API_HostAddress = http://localhost:5000

### Create antibiotic spectrum

POST http://localhost:5000/api/antibiotic-spectra
Accept: application/json

{
    name: "Beta-lactam",
    description: "Some description"
}
