<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3"/>
        <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.3.2" />
        <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="6.3.2" />
        <PackageReference Include="WolverineFx.Postgresql" Version="6.3.2" />
        <PackageReference Include="WolverineFx.FluentValidation" Version="6.3.2" />
        <PackageReference Include="WolverineFx" Version="6.3.2" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\RespiraAMS.Application\RespiraAMS.Application.csproj" />
      <ProjectReference Include="..\..\Infrastructure\RespiraAMS.Infrastructure\RespiraAMS.Infrastructure.csproj" />
    </ItemGroup>

</Project>
